---
title: "Hyphthesis Testing - Double Population"
author: "최호진(gansaw12@gmail.com)"
date: "2023.09.18(월)"
output:
  html_document:
  toc: yes
df_print: paged
word_document:
  toc: yes
pdf_document:
  extra_dependencies: kotex
fig_height: 6
fig_width: 10
toc: yes
fig_caption: yes
number_sections: yes
---

<br>
<br>



## 1. : 된장의 다이어트 효능

<br>

바이오벤처 기업인 D사에서는 다이어트에 관해 괄목할만한 효과가 있는 된장을 만들었다. 이러한 D사의 된장이 체중감량에 탁월한 효ㅕ과가 있는지 검정하기 위하여 20명을 실험대상으로 선발하여 된장 섭취 전과 후의 체중변화를 살펴보았다. 그 결과 평균 2.55kg이 감량되었을을 알 수 있었다. 또한 감량 무게의 표준편차는 3.13으로 측정되었다. 이러한 표본조사  결과를 이용하여 과연 D사의 된장이 다이어트 효과가 있다고 판단할 수 있는지를 5%의 유의수준에서 검정해 보시오.

<br>

#### 1. 평균과 표준편차가 주어진 경우
```{R}
n <- 20; xdbar <- 2.55; sigmad <- 3.13
t0 <- xdbar/(sigmad/sqrt(n))
pt(t0, df=n-1, lower.tail=F)
```
p-value 값이 유의수준 5%보다 낮음 => 귀무가설 기각

<br>

#### 2. 평균, 표준편차가 주어지지 않고 표본만 주어진 경우
모집단 1 : before, 모집단 2 : after
```{R}
before <- c(82, 54, 74, 75, 71, 76, 70, 62, 77, 75, 72, 83, 78, 74, 68, 76, 75, 75, 75, 71)
after <- c(75, 50, 74, 71, 69, 73, 68, 62, 68, 72, 70, 77, 71, 74, 67, 73, 77, 71, 76, 74)
t.test(before, after, paired=T, alt="greater")
```
p-value 값이 유의수준 5%보다 낮음 => 귀무가설 기각

<br>

#### 3. read.csv로 불러오기
```{R}
diet <- read.csv("https://www.dropbox.com/s/anylurmkgmhqiuk/diet.csv?dl=1", header=F, col.names=c("id", "before", "after"))
t.test(diet$before, diet$after, paired=T, alt="greater")
```
p-value 값이 유의수준 5%보다 낮음 => 귀무가설 기각

<br>
<br>


## 2. 타이어 평균수명

<br>

A회사의 타이어와 B회사의 타이어 평균수명에 차이가 있는지를 검정하기 위하여 각 회사의 제품을 무작위로 30개씩 표본으로 추출하여 조사하였다 .표본조사 결과 A사에서 생산한 타이어의 평균수명은 48,500km이고 표준편차는 3,600km이다. 반면에 B사에서 생산한 타이어의 평균수명은 52,000km이고 표준편차는 4,200km이었다. 두 타이어 회사의 분산이 다르다는 전제하에서 유의수준(a)을 0.05로 하여 두 회사 타이어의 평균수명에 차이가 있는지를 검정하시오.

<br>

#### 1. var.test(적절하지 않은 방법)
문제에서는 분산이 다르다는 전제를 하였지만 var.test는 등분산성을 조건으로 한다.
```{R}
tire <- read.csv("https://www.dropbox.com/s/d40dcuescate4nq/tire.csv?dl=1", header=F, col.names=c("id", "span"))
var.test(tire[tire$id==1,2], tire[tire$id==2,2])
```

<br>

#### 2. t.test(적절한 방법)
var.equal = F를 통해 분산이 다르다는 전제를 하였다.
등분산성을 전제로 한다면 var.equal = T로 하면 된다.
```{R}
t.test(tire[tire$id==1,2], tire[tire$id==2,2], var.equal=F)
```
p-value 값이 유의수준 5%보다 낮음 => 귀무가설 기각