---
title: "Hypothesize and Cluster iris dataset by using R"
author: "최호진(gansaw12@gmail.com)"
date: "2023.07.10(월)"
output:
  html_document:
    toc: yes
    df_print: paged
  word_document:
    toc: yes
  pdf_document:
    extra_dependencies: kotex
    fig_height: 6
    fig_width: 10
    toc: yes
    fig_caption: yes
    number_sections: yes
---




# I. 서론
- 유명 데이터셋인 Iris를 활용하여 가설검정을 진행한다. 유의수준(α)는 0.05(5%)로 진항하였다.
- 가설검정 결과 귀무가설을 기각하는 항목을 추출한다.
- 거리법을 통해 최적의 군집 수(k)를 구하고 k-means 군집분석을 진행한다.
- 분석 결과를 결론 항목에 도출한다.



## a. 패키지
```R
install.packages("tidyverse")
install.packages("NbClust")
install.packages("cluster")
install.packages("dplyr")
```

```R
library(tidyverse)
library(NbClust)
library(cluster)
library(dplyr)
```



# II. 탐색적 데이터 분석(EDA)

> 전처리 및 데이터 분석을 진행하기 전 데이터셋이 어떻게 구성되어있는지 확인해야 한다.
iris 데이터를 불러오고 전반적인 구조를 파악한다.

```{R}
df_iris <- iris     # Iris 데이터를 불러온다.
```

```{R}
colnames(df_iris)     # Iris 열의 이름을 확인할 수 있다.
```

```{R}
head(df_iris)     # Iris 열 상위 6개를 확인할 수 있다.
```

```{R}
str(df_iris)     # Iris 데이터의 형태를 확인할 수 있다.
```

```{R}
summary(df_iris)     # Iris의 요약본을 확인할 수 있다.
```

Iris의 데이터는 다음과 같이 분류되어 있다.
1. Sepal - length, width
2. Petal - length, width
3. Species - setosa, versicolor, virginica


 위 데이터를 이용하여 가설검정 및 데이터 분석을 진행하여야 하는데 그 전의 과정이 필요하다.
바로 데이터 전처리 과정이다.

# III. 데이터 전처리 (Data preprocessing)

> 데이터를 파악한 이후 데이터 전처리를 수항할 때 가장 먼저 하는 일은 결측치, 이상치를 처리하는 일이다.

## a. 결측치 처리

결측치를 처리하기 위해서는 결측치를 제거하거나 정제하는 방법이 있다.
결측치 유무를 확인하는 코드를 작성한 결과 결측치는 존재하지 않았다. 이에 따라 따로 제거하거나 정제하는 과정은
거치지 않았다.

```{R}
table(is.na(df_iris))
```

## b. 이상치 처리

데이터 분석의 정확성을 향상시키고 모델의 안정화를 위해 이상치를 처리하여야 한다.
이상치를 처리하는 방법은 여러가지 있는데 그 중에서 z-score normalization을 사용하기로 하였다.

```{R}
# 변수 추출

library(tidyverse)
vars <- names(df_iris)[1:4]

# z-score 정규화
zscore_iris <- df_iris %>% 
  mutate(across(all_of(vars), scale))

# 데이터 프레임으로 변환
df_zscore_iris <- as.data.frame(zscore_iris)

# 그래프 생성

df_zscore_iris %>% 
  pivot_longer(cols = all_of(vars), names_to = "variable", values_to = "value") %>%
  ggplot(aes(x = value)) +
  geom_density(aes(fill = variable), alpha = 0.5) +
  facet_wrap(~ variable, scales = "free") +
  labs(title = "Iris dataset by z-score normalization", x = "z-score", y = "density") +
  theme_bw()
```

일반적으로 표준편차가 3 이상이거나 -3 미만인 경우 일반적으로 이상치로 구분한다. 이상치를 처리한 결과 다음과 같다.

```{R}
filtered_iris <- iris[abs(zscore_iris[1:4]) < 3, ]     # 이상치들을 NA로 전환한다.
filtered_iris <- na.omit(filtered_iris)     # NA값을 제거한다.
head(filtered_iris)
```



# IV. 가설검정

> 전처리 과정을 마치고 본격적으로 가설검정에 들어간다. 1:4 열의 데이터가 Species와 관련이 있는지를 검정해보았다.

>a. Sepal.Length - Species
 - 귀무가설(H0) : 꽃받침 길이와 품종은 서로 관련이 없다.
 - 연구가설(H1) : 꽃받침 길이과 품종은 서로 관련이 있다.
 
>b. Sepal.Width - Species
 - 귀무가설(H0) : 꽃받침 너비와 품종은 서로 관련이 없다.
 - 연구가설(H1) : 꽃받침 너비와 품종은 서로 관련이 있다.
 
>c. Petal.Length - Species
 - 귀무가설(H0) : 꽃잎 길이와 품종은 서로 관련이 없다.
 - 연구가설(H1) : 꽃잎 길이와 품종은 서로 관련이 있다.
 
>d. Petal.Length - Species
 - 귀무가설(H0) : 꽃잎 너비와 품종은 서로 관련이 없다.
 - 연구가설(H1) : 꽃잎 너비와 품종은 서로 관련이 있다.
 
 
 > 현재 Species를 살펴보면 품종이 3종류로 구성되어 있다.
 따라서 3품종 간 차이를 검정하기 위해서 분산분석(ANOVA)를 이용하여 가설검정을 진행하였다.
 그리고 factor가 Species 1개이기 때문에 분산분석 중 일원분산분석을 이용하였다.
 

## a. Sepal.Length - Species 
```{R}
lm.sl_filtered_iris <- lm(Sepal.Length ~ factor(Species), data = filtered_iris)
anova_sl_result <- anova(lm.sl_filtered_iris)

print(anova_sl_result)
```
 
## b. Sepal.Width - Species 
```{R}
lm.sw_filtered_iris <- lm(Sepal.Width ~ factor(Species), data = filtered_iris)
anova_sw_result <- anova(lm.sw_filtered_iris)

print(anova_sw_result)
```
 
## c. Petal.Length - Species 
```{R}
lm.pl_filtered_iris <- lm(Petal.Length ~ factor(Species), data = filtered_iris)
anova_pl_result <- anova(lm.pl_filtered_iris)

print(anova_pl_result)
```
 
## d. Petal.Width - Species 
```{R} 
lm.pw_filtered_iris <- lm(Petal.Width ~ factor(Species), data = filtered_iris)
anova_pw_result <- anova(lm.pw_filtered_iris)

print(anova_pw_result)
```

## e. 가설검정 결과

> 4가지 가설 모두 Pr(>F) 부분이 다음과 같이 출력된다. (2.2e-16 ***)
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1 를 참조하면
위 가설 모두 유의수준 0.001 이내에서 매우 통계적으로 유의하다는 것을 알 수 있다.
따라서 귀무가설을 기각하고 연구가설을 채택한다.
=> 결론 : 꽃받침(길이, 너비), 꽃잎(길이, 너비) 모두 품종과 관련이 있다.
 
 
# V. 군집분석
> 그렇다면 실제로 위 가설이 검증되었는지 확인하기 위해 군집분석을 진행하였다. set.seed를 통해 난수를 생성하고 난수를 생성한 결과 군집이 제대로 이루어지는지 가장 보편적으로 사용하는 k-means군집분석을 이용하였다.
k-means 군집분석은 주어진 데이터를 k개의 클러스터로 그룹화하는 비지도 학습 기법이다. 이 알고리즘은 데이터 포인트들을 각각 가장 가까운 중심점(centroid)으로 할당하고, 할당된 포인트들을 기반으로 새로운 중심점을 계산하는 과정을 반복하여 클러스터의 중심점을 최적화하는 과정을 거친다.
  
```{R}
library(NbClust)

# 사용할 데이터셋 지정 (Species는 사용하지 않으므로 제외한다)
df_iris2 <- filtered_iris[,-5]

# 랜덤으로 표본을 뽑는 규칙 설정 => 일관된 결과를 얻을 수 있다.
set.seed(1000)
nc2 <- NbClust(df_iris2, distance="euclidean", min.nc=3, max.nc=15, method="kmeans")
```

the best number of clusters is  3 이라는 문구를 통해 최적의 k값은 3이라는 것을 확인할 수 있었다.
이제 이 k 값을 이용하여 clustering을 진행하였다.

## a. 분석 결과

```{R}
km_iris2 <- kmeans(df_iris2, centers=3, nstart=10)     # nstart: iteration 횟수 제약을 의미한다.
km_iris2
```

## b. 시각화

군집분석을 clusplot을 이용하여 시각화하였다.

```{R}
# clusplot
library(cluster)
clusplot(x=df_iris2, clus=km_iris2$cluster, color=T, shade=T, labels=2, lines=0) 
```



# VI. 결론
  
>  NbClust를 통해 최적의 k값을 결정하였고 k-means 알고리즘을 적용하여 데이터 포인트가 3개의 cluster로 구분되었다.
그리고 시각화를 통해 cluster 간 분포와 경계를 확인할 수 있었다.
위 clusplot을 통해 두 구성요소 간 95.81%로 변동성에 영향이 강하다는 것을 확인할 수 있다. 다시 말하자면 위 모델은 데이터셋의 구조를 잘 요약하고 있다는 것을 의미한다. 따라서 위 모델을 통해 데이터의 구조와 패턴을 파악하는데 도움이 되었고 위 clustering을 통하여 추가적인 분석이나 의사결정에 활용되는데 도움을 줄 수 있다고 볼 수 있다.
  